site_name: Project Plateform
pages:
- ['index.md', 'Home']
- ['about.md', About]
- ['design/getting-started/design-principles.md', 'Getting started', 'Design Principles']
- ['design/style/devices-display.md', 'Style', 'Devices and displays']
- ['design/style/themes.md', 'Style', 'Themes']
- ['design/style/grid.md', 'Style', 'Grid']
- ['design/style/typography.md', 'Style', 'Typography']
- ['design/style/color.md', 'Style', 'Color']
- ['design/style/iconography.md', 'Style', 'Iconography']
- ['design/style/branding.md', 'Style', 'Branding']
theme: readthedocs